### ISSUE TITLE
just produces a red square border

### ISSUE THREAD

**Issue by Jan-Jan** [maxs15/react-native-spinkit#25]
Thank you for react-native-spinkit

If I use it with react-native 0.28, all that gets produced is a red square border. The size can be changed with the size parameter, but nothing gets displayed beyond that.

**Comment by ronnpang1** [comment]
Can you explain how you fixed this? I am running into this issue now as well.

**Comment by karan101292** [comment]
any update? I am using react native 0.44

**Comment by karan101292** [comment]
solved it. There is a problem with `rnpm link react-native-spinkit`. Sometimes it adds RNSpinkitPackage dependency to MainActivity.java instead of MainApplication.java

Solution:
Follow this step manually
https://github.com/maxs15/react-native-spinkit/wiki/Manual-linking---Android#in-androidappsrcmainjavacomexamplemainapplicationjava-add-the-rnspinkitpackage-dependency
